package tema3.ejercicio1.pojos;
// Generated 08-ene-2018 9:40:03 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Departamento generated by hbm2java
 */
public class Departamento  implements java.io.Serializable {


     private int id;
     private String dnombre;
     private Set<Empleado> empleados = new HashSet(0);
     private Direccion direccion;
     private Empleado jefe;

    public Departamento() {
    }

	
    public Departamento(int id, String dnombre) {
        this.id = id;
        this.dnombre = dnombre;
    }
    public Departamento(int id, String dnombre, Set<Empleado> empleados) {
       this.id = id;
       this.dnombre = dnombre;
       this.empleados = empleados;
    }

    public Departamento(int id, String dnombre, Direccion direccion) {
        this.id = id;
        this.dnombre = dnombre;
        this.direccion = direccion;
    }

    public Departamento(int id, String dnombre, Direccion direccion, Empleado jefe) {
        this.id = id;
        this.dnombre = dnombre;
        this.direccion = direccion;
        this.jefe = jefe;
    }
    
    
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    public Direccion getDireccion() {
        return direccion;
    }

    public void setDireccion(Direccion direccion) {
        this.direccion = direccion;
    }

    public Empleado getJefe() {
        return jefe;
    }

    public void setJefe(Empleado jefe) {
        this.jefe = jefe;
    }
    
    public String getDnombre() {
        return this.dnombre;
    }
    
    public void setDnombre(String dnombre) {
        this.dnombre = dnombre;
    }
    public Set<Empleado> getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Set<Empleado> empleados) {
        this.empleados = empleados;
    }




}


