package Examenes.trimestre2.ex3.redsocial.pojos;
// Generated 05-feb-2018 8:38:39 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.Set;

/**
 * Lider generated by hbm2java
 */
public class Lider  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private Date fechaAlta;
     private Set<Seguidor> seguidores;
     private int nMG;

    public Lider() {
    }

    public Lider(String nombre, Date fechaAlta) {
       this.nombre = nombre;
       this.fechaAlta = fechaAlta;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Date getFechaAlta() {
        return this.fechaAlta;
    }
    
    public void setFechaAlta(Date fechaAlta) {
        this.fechaAlta = fechaAlta;
    }

    public Set<Seguidor> getSeguidores() {
        return seguidores;
    }

    public void setSeguidores(Set<Seguidor> seguidores) {
        this.seguidores = seguidores;
    }

    public int getnMG() {
        return nMG;
    }

    public void setnMG(int nMG) {
        this.nMG = nMG;
    }


}


