package Examenes.trimestre2.ex3.redsocial.pojos;
// Generated 05-feb-2018 8:38:39 by Hibernate Tools 4.3.1



/**
 * Seguidor generated by hbm2java
 */
public class Seguidor  implements java.io.Serializable {


     private Integer id;
     private String nick;
     private String correo;
     private String pais;

    public Seguidor() {
    }

    public Seguidor(String nick, String correo, String pais) {
       this.nick = nick;
       this.correo = correo;
       this.pais = pais;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNick() {
        return this.nick;
    }
    
    public void setNick(String nick) {
        this.nick = nick;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getPais() {
        return this.pais;
    }
    
    public void setPais(String pais) {
        this.pais = pais;
    }




}


